### ISSUE TITLE
Authentication Policy  per Organization

### ISSUE THREAD

**Issue by olivier34000** [p2-inc/phasetwo#10]
Hello,

I don't know if it' a right place to ask the question but I would like to know if you want to have the possibility to link the authentication policies (like the password policy) to a organization. Currently the policy is linked to a realm. Is-it in the roadmap or not ? Do you have suggestions to answer to this use-case ?

**Comment by xgp** [comment]
> Is-it in the roadmap or not ?

No.

> Do you have suggestions to answer to this use-case ?

Realm per tenant.
