### ISSUE TITLE
Login via Magic Code sent by Email 

### ISSUE THREAD

**Issue by thebestgin** [p2-inc/phasetwo#3]
Magic Code feature, which send a login / register code via email. 

Idea: Hash(creation time of the code + code + salt) = hash. You save this hash and the creation time of the code as cookies or response it with the Magic Code input form to check against after submit. 

Simular extensions to integrate in phase two or use as inspiration :
https://github.com/mesutpiskin/keycloak-2fa-email-authenticator
https://gitlab.com/niroj.adhikary/keycloak-email-otp/-/tree/master

**Comment by xgp** [comment]
This is released as part of our magic link extension:
- https://github.com/p2-inc/keycloak-magic-link#email-otp
- https://keycloak.discourse.group/t/magic-link-login-authenticator-and-resource/15311/8
- https://repo1.maven.org/maven2/io/phasetwo/keycloak/keycloak-magic-link/0.10/

**Comment by xgp** [comment]
https://github.com/p2-inc/keycloak-magic-link/commit/50b72560e4d772e660e517d34373e0099c2baf6c
