### ISSUE TITLE
“remember me” functionality for social providers

### ISSUE THREAD

**Issue by thebestgin** [p2-inc/phasetwo#4]
It is a pity that the native Keycloak does not include this basic function; “remember me” functionality for social providers

It would be great if you provide that.

Without this feature the identity providers are annoying for the user, especially when I am logged in with multiple google accounts in the web browser for example. It always asks which google account I want to continue with. 
In this case, the classic email login is the most convenient in Keycloak.

It exists a Extension for that.
The Implementation is very simple.
https://github.com/Herdo/keycloak-remember-me-authenticator

**Comment by xgp** [comment]
Thanks for the suggestion. We're happy to accept PRs for such features.
