### ISSUE TITLE
Missing Locale Setting

### ISSUE THREAD

**Issue by thebestgin** [p2-inc/phasetwo#5]
In Phase2 full managed Service the local setting is missing.
)s that normal?
![image](https://user-images.githubusercontent.com/10037845/228892642-bc692495-721e-46b9-9bd3-f29b6373cd00.png)

**Comment by xgp** [comment]
What locales do you have set in Realm Settings?
![image](https://user-images.githubusercontent.com/244253/228915820-99619c94-90c7-4d4c-8fab-969fc0ea68ff.png)
You have to select which locales you want to support, then they will be available to select for the user.

**Comment by thebestgin** [comment]
Is selected:
![image](https://user-images.githubusercontent.com/10037845/228916668-bfd5c886-161e-4847-84f8-aed041a10360.png)

User:
![image](https://user-images.githubusercontent.com/10037845/228916944-510d79b3-01df-4b19-aef6-f40150a26f5c.png)

**Comment by xgp** [comment]
Ah. You are asking why it isn't present in the new Keycloak Admin UI, not p2 versus kc. They did not implement a locale selector in the new version of the Admin UI, on which the p2 Admin UI is built. If you want that selector, you can switch your admin theme back to `keycloak` using the realm settings.

**Comment by thebestgin** [comment]
Thanks.
