### ISSUE TITLE
Suggestion: Returning IDs of created objects within api

### ISSUE THREAD

**Issue by paulwer** [p2-inc/phasetwo#6]
For Example: when creating a new organization, we have to fetch organizations afterwards and look for the id, which was givven by the system. It would be better if the return type is not void and instead the id of the organization or the OrganizationRepresentation.

Please check also for other elements, if this is necessary there.
Thank you.

**Comment by xgp** [comment]
Every method that creates an object in the API returns the ID in the `Location` header.

**Comment by paulwer** [comment]
@xgp the javascript-sdk at least will not return this in the result of the method. please add this as return-value.

Example: `javascript-sdk (p2) => createOrganization :: returns Promise<void>`
Example: `keycloak-admin-sdk => createUser :: returns Promise<{ id: string; }>`

you may have to check if the other libraries already support this or if the have to be updated as well.

thank you

**Comment by xgp** [comment]
Every method has a `*Raw` version, which returns a `Promise<runtime.ApiResponse<void>>`, which you can use to get the response header values.

**Comment by paulwer** [comment]
@xgp i understand. It would be great eigher to have this available or documented.

for the "normal user" its quite unclear, why this is not returned.
