### ISSUE TITLE
Free Version: Admin Portal and IdP Wizard reload infinitely

### ISSUE THREAD

**Issue by JenniferHeik** [p2-inc/phasetwo#9]
As the title says, I just wanted to check out your demo and was thrown off by that bug

**Comment by xgp** [comment]
This is fixed. Which image are you using?

**Comment by JenniferHeik** [comment]
I am not using any image, I just created an account in your hosted free version and a deployment in the shared cluster, so I dont`t really know whats causing the issue. You could replicate by just creating an account in your hosted free version

**Comment by xgp** [comment]
Thanks. Which region are you using?

**Comment by xgp** [comment]
@JenniferHeik we released a patch to the `eu-central-1` shared cluster. Can you please try again and see if you get the same behavior? Also, please do a hard browser refresh, as it may be the result of some cached assets.

**Comment by JenniferHeik** [comment]
Europe--Gesendet mit der WEB.DE Mail AppAm 17.07.24, 17:49 schrieb Garth ***@***.***>:

   
  Thanks. Which region are you using?
